name: Create release (reusable)

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      release_type:
        required: true
        type: string

permissions:
  contents: write
  actions: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release branch
        run: |
          git config user.name "github-actions[ci]"
          git config user.email "ci@pyrodactyl.dev"
          git checkout -b releases/v${{ inputs.version }}

      - name: Update version in config/app.php
        run: |
          sed -i "s/'version' => '.*'/'version' => 'v${{ inputs.version }}'/g" config/app.php

      - name: Commit version bump
        run: |
          git add config/app.php
          git commit -m "ci: bump v${{ inputs.version }}"

      - name: Push release branch
        run: git push origin releases/v${{ inputs.version }}

      # ---- Build tarball -------------------------------------------------
      - name: Create release archive
        run: |
          rm -rf node_modules tests CODE_OF_CONDUCT.md CONTRIBUTING.md \
                 flake.lock flake.nix phpunit.xml shell.nix
          tar -czf panel.tar.gz \
              --exclude='.*' * .editorconfig .env.example .gitignore .prettierrc.json

      - name: Generate checksum
        id: checksum
        run: |
          SUM=$(sha256sum panel.tar.gz)
          echo "$SUM" > checksum.txt
          echo "checksum=$(echo $SUM | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      # ---- GitHub Release ------------------------------------------------
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2   # v2 is the current stable
        with:
          tag_name: v${{ inputs.version }}
          target_commitish: releases/v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: ${{ inputs.release_type == 'prerelease' }}
          files: |
            panel.tar.gz
            checksum.txt
          body: |
            **SHA256 checksum:**
